import { Activity, ActivityCategory } from '../domain/entities/Activity';
import { Goal } from '../domain/entities/Goal';

/** The full forecast report generated by the ForecastService. */
export interface ForecastReport {
  /** Estimated total emissions for the next month in kg CO2e. */
  nextMonthEstimate: number;
  /** Whether emissions are trending up, down, or holding steady. */
  trendDirection: 'increasing' | 'decreasing' | 'stable';
  /** Percentage change compared to the prior 15-day period (positive = increase). */
  trendPercentage: number;
  /** Probability (0–100) of achieving the user's monthly CO2 goal. */
  goalAchievementProbability: number;
  /** Categories where emissions increased significantly and pose a risk. */
  riskAreas: { category: ActivityCategory; percentageIncrease: number; message: string }[];
  /** Personalized improvement suggestions based on current trends. */
  improvementOpportunities: string[];
}

/**
 * Service: Generate a forward-looking carbon emission forecast for a user.
 *
 * Splits the last 30 days of activity into two 15-day windows (recent vs. prior),
 * computes a trend, and projects next month's emissions. Risk areas and improvement
 * opportunities are derived in a single pass over the category data for efficiency.
 */
const DEFAULT_MONTHLY_ESTIMATE_KG = 480;
const DAYS_IN_WINDOW = 15;
const DAYS_IN_MONTH = 30;
const SCALE_FACTOR_15_TO_30 = 2;
const TREND_THRESHOLD_PCT = 5;
const GOAL_HIGH_PROBABILITY = 70;
const GOAL_LOW_PROBABILITY = 50;
const GOAL_BUFFER_WEIGHT = 30;
const GOAL_EXCESS_WEIGHT = 50;
const RISK_INCREASE_THRESHOLD_PCT = 10;
const NEW_EMISSION_THRESHOLD_KG = 20;
const TRANSPORT_PROPORTION_THRESHOLD = 0.4;
const FOOD_PROPORTION_THRESHOLD = 0.3;
const ENERGY_PROPORTION_THRESHOLD = 0.3;

export class ForecastService {
  /**
   * Generate a forecast report from historical activity data.
   *
   * @param userActivities - All recent activities for the user (typically last 30 days).
   * @param currentGoal - The user's active monthly CO2 reduction goal, or null if none set.
   * @returns A ForecastReport with trend analysis and personalized improvement suggestions.
   */
  static generate(userActivities: Activity[], currentGoal: Goal | null): ForecastReport {
    const defaultEstimate = DEFAULT_MONTHLY_ESTIMATE_KG;

    if (userActivities.length === 0) {
      return {
        nextMonthEstimate: defaultEstimate,
        trendDirection: 'stable',
        trendPercentage: 0,
        goalAchievementProbability: currentGoal ? 50 : 0,
        riskAreas: [],
        improvementOpportunities: ['Log your first activity to start generating personalized forecasts!'],
      };
    }

    // Time boundaries
    const now = new Date();
    const fifteenDaysAgo = new Date(now.getTime() - DAYS_IN_WINDOW * 24 * 60 * 60 * 1000);
    const thirtyDaysAgo = new Date(now.getTime() - DAYS_IN_MONTH * 24 * 60 * 60 * 1000);

    // Aggregate emissions in a SINGLE PASS over the activities array
    let recentEmissions = 0;
    let priorEmissions = 0;

    const recentCategoryEmissions: Record<ActivityCategory, number> = {
      transport: 0,
      energy: 0,
      food: 0,
      shopping_waste: 0,
    };
    const priorCategoryEmissions: Record<ActivityCategory, number> = {
      transport: 0,
      energy: 0,
      food: 0,
      shopping_waste: 0,
    };

    const fifteenDaysAgoTime = fifteenDaysAgo.getTime();
    const thirtyDaysAgoTime = thirtyDaysAgo.getTime();
    const nowTime = now.getTime();

    for (const act of userActivities) {
      const actTime = act.timestamp.getTime();
      if (actTime >= fifteenDaysAgoTime && actTime <= nowTime) {
        recentEmissions += act.co2Emissions;
        recentCategoryEmissions[act.category] += act.co2Emissions;
      } else if (actTime >= thirtyDaysAgoTime && actTime < fifteenDaysAgoTime) {
        priorEmissions += act.co2Emissions;
        priorCategoryEmissions[act.category] += act.co2Emissions;
      }
    }

    // Scale 15-day recent window to 30 days for a full-month projection
    const recent30DayScaled = recentEmissions * SCALE_FACTOR_15_TO_30;
    let nextMonthEstimate = recent30DayScaled === 0 ? defaultEstimate : recent30DayScaled;

    // Calculate trend percentage and direction
    let trendPercentage = 0;
    let trendDirection: 'increasing' | 'decreasing' | 'stable' = 'stable';

    if (priorEmissions > 0) {
      trendPercentage = Math.round(((recentEmissions - priorEmissions) / priorEmissions) * 100 * 10) / 10;
      if (trendPercentage > TREND_THRESHOLD_PCT) {
        trendDirection = 'increasing';
      }
      if (trendPercentage < -TREND_THRESHOLD_PCT) {
        trendDirection = 'decreasing';
      }
    }

    // Factor trend into next-month projection
    nextMonthEstimate = Math.round(nextMonthEstimate * (1 + trendPercentage / 100) * 10) / 10;
    if (nextMonthEstimate < 0) nextMonthEstimate = 0;

    // Goal achievement probability
    let goalAchievementProbability = currentGoal ? 100 : 0;
    if (currentGoal) {
      const target = currentGoal.targetCo2;
      if (nextMonthEstimate <= target) {
        const buffer = target - nextMonthEstimate;
        goalAchievementProbability = Math.min(
          100,
          Math.round(GOAL_HIGH_PROBABILITY + (buffer / target) * GOAL_BUFFER_WEIGHT),
        );
      } else {
        const excess = nextMonthEstimate - target;
        goalAchievementProbability = Math.max(
          0,
          Math.round(GOAL_LOW_PROBABILITY - (excess / target) * GOAL_EXCESS_WEIGHT),
        );
      }
    }

    // Identify risk areas AND generate improvement opportunities in a SINGLE LOOP
    const riskAreas: ForecastReport['riskAreas'] = [];
    const improvementOpportunities: string[] = [];

    (Object.keys(recentCategoryEmissions) as ActivityCategory[]).forEach((cat) => {
      const recent = recentCategoryEmissions[cat];
      const prior = priorCategoryEmissions[cat];

      // Risk area detection
      if (recent > 0 && prior > 0) {
        const increasePct = ((recent - prior) / prior) * 100;
        if (increasePct > RISK_INCREASE_THRESHOLD_PCT) {
          riskAreas.push({
            category: cat,
            percentageIncrease: Math.round(increasePct),
            message: `Emissions from ${cat} increased by ${Math.round(increasePct)}% compared to the previous fortnight.`,
          });
        }
      } else if (recent > NEW_EMISSION_THRESHOLD_KG && prior === 0) {
        riskAreas.push({
          category: cat,
          percentageIncrease: 100,
          message: `New emission activity detected in ${cat} this week.`,
        });
      }

      // Category-specific improvement opportunities
      if (cat === 'transport' && recent * SCALE_FACTOR_15_TO_30 > recent30DayScaled * TRANSPORT_PROPORTION_THRESHOLD) {
        improvementOpportunities.push(
          'Transport accounts for a high proportion of your footprint. Try combining errands or carpooling.',
        );
      }
      if (cat === 'food' && recent * SCALE_FACTOR_15_TO_30 > recent30DayScaled * FOOD_PROPORTION_THRESHOLD) {
        improvementOpportunities.push(
          'Food emissions are above target. Incorporating more plant-based days is the fastest way to drop this.',
        );
      }
      if (cat === 'energy' && recent * SCALE_FACTOR_15_TO_30 > recent30DayScaled * ENERGY_PROPORTION_THRESHOLD) {
        improvementOpportunities.push(
          'Household energy is high. Ensure heating settings are optimized and appliances are unplugged.',
        );
      }
    });

    // Add a general trend-based tip
    if (trendDirection === 'increasing') {
      improvementOpportunities.unshift(
        'Emissions are trending upward. Consider swapping one car trip a day to counter the rise.',
      );
    } else if (trendDirection === 'decreasing') {
      improvementOpportunities.unshift(
        'Great job! Emissions are trending down. Keep maintaining your car-free or plant-based logs.',
      );
    } else {
      improvementOpportunities.unshift(
        'Emissions are stable. Look for easy wins like swapping to energy-saving appliances.',
      );
    }

    return {
      nextMonthEstimate,
      trendDirection,
      trendPercentage,
      goalAchievementProbability,
      riskAreas,
      improvementOpportunities,
    };
  }
}
